### PR TITLE
Adds dynamic group name option

### PR DESCRIPTION
**Pull request by aziztitu**
I came across an issue where my AAD group names were returned on a different field than the one used by this plugin. Hence, I updated it to use a dynamic field from the config.

### CODE REVIEW

**Comment by aziztitu** [comment]
Let me know if this looks good, and how quickly this can be published. I'd rather not publish a new version of the plugin just to fix this one issue :D

**Comment by IhToN** [comment]
It looks good, I'll try to make a release including this small patch during the week.

Thanks!

**Comment by aziztitu** [comment]
@IhToN  Were you able to create a new release?

**Comment by IhToN** [comment]
Sorry @aziztitu I totally forgot. I've just made a new 1.1.0 release. It should be available on npm already.

**Comment by aziztitu** [comment]
Awesome. Thanks @IhToN

**Pull request merged**
